project:
  type: website
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
    - "!myresources/"
    - "!renv/"
    - "!certificate*"
    - "!posts/2025-02-25-exercises-in-quarto/test-quiz.Rmd"
    # - "!posts/2022-02-23-longitudinal-multilevel-bayes-2/"
  resources:
    - "files/"
#  post-render:
#    - makeredirects.R
  preview:
    port: 4321
    browser: true
    watch-inputs: false
execute:
  freeze: auto   # Re-render only when source changes
  echo: true #Include the source code in output
  message: false # don't show messages
  warning: false #don't include warnings in the output
  output: true #include the results of executing the code
  cache: false # don't cache code junks by default
description-meta: "Andreas Handel personal website."
editor: 
  markdown: 
    wrap: sentence
engine: knitr
filters:
   - include-code-files

website:
  title: "Sam Passmore"
  site-url: "https://www.sampassmore.com"
  repo-url: https://github.com/sampassmore/sampassmore_website
  description: "Website of Sam Passmore"
  favicon: /files/icon.png 
  google-analytics: ""
  cookie-consent: true    
  search: true
  navbar:
    background: "#99ccff"
    logo: /files/logo.png
    left:
      - text: "About"
        file: about.qmd
      - text: "Posts"
        file: posts.qmd
      - text: "Projects"
        file: projects.qmd
  page-footer:
    left: |
      {{< fa regular copyright >}} Sam Passmore, 2024<br>
      Website code forked from [Andreas Shandel](https://www.andreashandel.com).<br> 
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)<br>
      Opinions are my own and do not represent my employer
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [Source at {{< fa brands github >}} GitHub](https://github.com/sampassmore/sampassmore_website)
format:
  html:
    include-after-body: files/webex.js    
    code-fold: false
    #embed-resources: true	
    #self-contained: true
    theme: 
      light: [matria,files/customstyle.scss]
      dark: [slate,files/customstyle.scss]
    css: files/webex.css
    toc: true
    